FROM lqss/jenkins:admin

# Setup Jenkins init admin User
ENV JENKINS_USER admin
ENV JENKINS_PASS admin
COPY /groovy/default-user.groovy /usr/share/jenkins/ref/init.groovy.d/

# Setup Credentials
ENV ID id
ENV USER user
ENV PASSWORD pass
COPY /groovy/cred.groovy /usr/share/jenkins/ref/init.groovy.d/