name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}        
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true        
          context: .
          file: ./anonymous/Dockerfile
          tags: lqss/jenkins:anonymous