name: Variants Docker Images BUILD/PUSH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Build jenkins variants images
        run: ./build-scripts/variants-docker-build.sh

  # Push docker images
  docker-push:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Docker Login
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Push jenkins images
        run: ./build-scripts/variants-docker-push.sh
